version: "2"
run:
  build-tags:
    - integration
  modules-download-mode: readonly
  tests: true
output:
  formats:
    text:
      path: stdout
  sort-order:
    - linter
    - severity
    - file
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  disable:
    - depguard
    - exhaustruct
    - nonamedreturns
  settings:
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    govet:
      enable-all: true
    nolintlint:
      require-specific: true
      allow-unused: false
    tagliatelle:
      case:
        rules:
          header: header
          json: goCamel
          yaml: goCamel
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - exhaustruct
          - funlen
          - gocognit
          - ireturn
          - lll
          - maintidx
          - mnd
          - paralleltest
          - varnamelen
          - wrapcheck
        path: _test.go$
      - linters:
          - protogetter
        path: mocks.go$
      - linters:
          - govet
        path: _test.go$
        text: 'fieldalignment: struct ((with .+ pointer bytes)|(of size .+)) could be .+'
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - lll
        source: ^.+\s+`.+:".+"`
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/peczenyj/fmtquotecheck
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
